import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://wscan.dealopia.com/api/static?fileName=homepagedemosite&lastScannedDate=20240821"
          async
        ></Script>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
